version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    labels:
      - "type/deps"
      - "area/dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
      timezone: "America/Mexico_City"
    open-pull-requests-limit: 5
    labels:
      - "type/deps"
      - "area/ci"
