// <auto-generated />
using System;
using Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260724063011_PersistCatalogAggregate")]
    partial class PersistCatalogAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductOptionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name_key");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasAlternateKey("ProductId", "Id")
                        .HasName("ak_product_options_product_id_id");

                    b.HasIndex("ProductId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_product_options_product_display_order");

                    b.HasIndex("ProductId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("ux_product_options_product_name");

                    b.ToTable("product_options", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_options_display_order", "display_order >= 0");
                        });
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DiscontinuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discontinued_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_products_slug");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_products_lifecycle", "(\n    status = 'Draft'\n    AND published_at_utc IS NULL\n    AND discontinued_at_utc IS NULL\n)\nOR\n(\n    status = 'Published'\n    AND published_at_utc IS NOT NULL\n    AND discontinued_at_utc IS NULL\n)\nOR\n(\n    status = 'Discontinued'\n    AND discontinued_at_utc IS NOT NULL\n)");

                            t.HasCheckConstraint("ck_products_status", "status IN ('Draft', 'Published', 'Discontinued')");

                            t.HasCheckConstraint("ck_products_timestamp_order", "published_at_utc IS NULL\nOR discontinued_at_utc IS NULL\nOR discontinued_at_utc >= published_at_utc");

                            t.HasCheckConstraint("ck_products_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductVariantOptionRecord", b =>
                {
                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("ProductVariantId", "OptionId")
                        .HasName("pk_product_variant_options");

                    b.HasIndex("ProductId", "OptionId");

                    b.HasIndex("ProductId", "ProductVariantId");

                    b.ToTable("product_variant_options", "catalog");
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductVariantRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTimeOffset?>("DiscontinuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discontinued_at_utc");

                    b.Property<string>("OptionCombinationKey")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("option_combination_key");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasAlternateKey("ProductId", "Id")
                        .HasName("ak_product_variants_product_id_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_sku");

                    b.HasIndex("ProductId", "OptionCombinationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_product_combination_live")
                        .HasFilter("status <> 'Discontinued'");

                    b.ToTable("product_variants", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_product_variants_lifecycle", "(\r\n    status = 'Draft'\r\n    AND activated_at_utc IS NULL\r\n    AND discontinued_at_utc IS NULL\r\n)\r\nOR\r\n(\r\n    status = 'Active'\r\n    AND activated_at_utc IS NOT NULL\r\n    AND discontinued_at_utc IS NULL\r\n)\r\nOR\r\n(\r\n    status = 'Discontinued'\r\n    AND discontinued_at_utc IS NOT NULL\r\n)");

                            t.HasCheckConstraint("ck_product_variants_status", "status IN ('Draft', 'Active', 'Discontinued')");

                            t.HasCheckConstraint("ck_product_variants_timestamp_order", "activated_at_utc IS NULL\r\nOR discontinued_at_utc IS NULL\r\nOR discontinued_at_utc >= activated_at_utc");
                        });
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductOptionRecord", b =>
                {
                    b.HasOne("Catalog.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany("OptionDefinitions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_options_products");
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductVariantOptionRecord", b =>
                {
                    b.HasOne("Catalog.Infrastructure.Persistence.Records.ProductOptionRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId", "OptionId")
                        .HasPrincipalKey("ProductId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_options_option");

                    b.HasOne("Catalog.Infrastructure.Persistence.Records.ProductVariantRecord", null)
                        .WithMany("OptionSelections")
                        .HasForeignKey("ProductId", "ProductVariantId")
                        .HasPrincipalKey("ProductId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_options_variant");
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductVariantRecord", b =>
                {
                    b.HasOne("Catalog.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products");
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Navigation("OptionDefinitions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Catalog.Infrastructure.Persistence.Records.ProductVariantRecord", b =>
                {
                    b.Navigation("OptionSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
